sample_rate: 32000
frame_rate: 50
chunk_size: 1
window_size: 5
features: ["chroma"]
distance_func: "Euclidean"  # Euclidean for OLTWArzt, euclidean for OLTWDixon
max_run_count: 30
dataset: "asap"
algorithm: "oltw_arzt"