sample_rate_exp: [16000, 22050]
frame_rate_exp: [25, 50, 100]
window_size_exp: [1, 3, 5]
features_exp:
  - "chroma"
distance_func_exp: 
  - "euclidean"
  - "cosine"
  - "dice"
  - "braycurtis"
  - "canberra"
  - "chebyshev"
  - "cityblock"
  - "correlation"
  - "jensenshannon"
  - "minkowski"
  - "sqeuclidean"
